---
extends: default

ignore: |
  catalog/druid/chart/templates/

rules:
  line-length:
    max: 200
  truthy:
    check-keys: false
  document-start: disable
  comments:
    min-spaces-from-content: 1
