# Argo Events - Event sources and sensors

controller:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists

serviceAccount:
  create: false
  name: argo-events-controller-manager
