{{- range $sa := list "historical" "overlord" "broker" "msk-client" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: druid-{{ $sa }}
  labels:
    {{- include "common.labels" $ | indent 4 }}
  annotations:
    {{- include "common.annotations" $ | indent 4 }}
    {{- with (index $.Values.serviceAccounts (printf "druid-%s" $sa)) }}
    {{- if .roleArn }}
    eks.amazonaws.com/role-arn: {{ .roleArn }}
    {{- end }}
    {{- end }}
{{- end }}
