# Loki - Production overrides
# Production: longer retention, larger storage

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::351619759866:role/production-eks-loki

loki:
  commonConfig:
    replication_factor: 1
  limits_config:
    retention_period: 2160h

singleBinary:
  persistence:
    size: 100Gi
