# AWS Load Balancer Controller

replicaCount: 2

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists

podDisruptionBudget:
  minAvailable: 1

enableServiceMutatorWebhook: false

serviceAccount:
  create: false
  name: aws-load-balancer-controller
