# Velero - Dev overrides
# Dev: backups disabled, no node agent, no backup locations

configuration:
  backupStorageLocation: []
  volumeSnapshotLocation: []

deployNodeAgent: false

schedules:
  daily:
    disabled: true
  weekly:
    disabled: true
