# Velero - Staging overrides
# Staging: staging backup bucket

serviceAccount:
  server:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::351619759866:role/staging-eks-velero

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: aws-eks-staging-backups
      config:
        region: us-west-2
