apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: karpenter.sh/v1
      kind: NodePool
      metadata:
        name: default
      spec:
        limits:
          cpu: 75
          memory: 150Gi

configMapGenerator:
  - name: karpenter-config
    literals:
      - CLUSTER_NAME=staging-eks
      - ENVIRONMENT=staging
