# Argo Workflows - Dev overrides
# Single replica, dev artifact bucket

server:
  replicas: 1
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::351619759866:role/dev-eks-argo-workflows

artifactRepository:
  s3:
    bucket: aws-eks-dev-argo-artifacts
